"""empty message

Revision ID: 484fe0160426
Revises: 7ce8e044c055
Create Date: 2016-02-06 19:08:32.367651

"""

# revision identifiers, used by Alembic.
revision = '484fe0160426'
down_revision = '7ce8e044c055'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_song_assoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('track_order', sa.Integer(), nullable=True),
    sa.Column('song_notes', sa.Text(), nullable=True),
    sa.Column('show_set', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id', 'show_id', 'song_id')
    )
    op.drop_table('show_associations')
    op.drop_constraint(u'songs_ibfk_1', 'songs', type_='foreignkey')
    op.drop_column('songs', 'set_desc')
    op.drop_column('songs', 'show_id')
    op.drop_column('songs', 'loc_city')
    op.drop_column('songs', 'loc_state')
    op.drop_column('songs', 'longitude')
    op.drop_column('songs', 'latitude')
    op.drop_column('songs', 'loc_zip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('loc_zip', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('songs', sa.Column('latitude', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('songs', sa.Column('longitude', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('songs', sa.Column('loc_state', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('songs', sa.Column('loc_city', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('songs', sa.Column('show_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('set_desc', mysql.VARCHAR(length=80), nullable=True))
    op.create_foreign_key(u'songs_ibfk_1', 'songs', 'shows', ['show_id'], ['id'])
    op.create_table('show_associations',
    sa.Column('show_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('song_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['show_id'], [u'shows.id'], name=u'show_associations_ibfk_1'),
    sa.ForeignKeyConstraint(['song_id'], [u'songs.id'], name=u'show_associations_ibfk_2'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('show_song_assoc')
    ### end Alembic commands ###
