"""empty message

Revision ID: 6a97fb1ae83d
Revises: a0c516b8f093
Create Date: 2016-02-15 22:39:32.961457

"""

# revision identifiers, used by Alembic.
revision = '6a97fb1ae83d'
down_revision = 'a0c516b8f093'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'songs', ['system_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    ### end Alembic commands ###
