"""empty message

Revision ID: 7af9adda1b64
Revises: 99b6290c33f7
Create Date: 2016-02-27 21:37:10.579829

"""

# revision identifiers, used by Alembic.
revision = '7af9adda1b64'
down_revision = '99b6290c33f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    ### end Alembic commands ###
