"""empty message

Revision ID: 7ce8e044c055
Revises: 016bcaf3364e
Create Date: 2016-02-03 19:41:42.405130

"""

# revision identifiers, used by Alembic.
revision = '7ce8e044c055'
down_revision = '016bcaf3364e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('system_name', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'system_name')
    ### end Alembic commands ###
