"""empty message

Revision ID: 99b6290c33f7
Revises: de99292ab116
Create Date: 2016-02-27 19:01:47.802032

"""

# revision identifiers, used by Alembic.
revision = '99b6290c33f7'
down_revision = 'de99292ab116'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'shows_ibfk_1', 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'shows_ibfk_1', 'shows', 'venues', ['venue_id'], ['id'])
    ### end Alembic commands ###
