"""empty message

Revision ID: a0c516b8f093
Revises: cf888d3f2a72
Create Date: 2016-02-14 16:59:32.592845

"""

# revision identifiers, used by Alembic.
revision = 'a0c516b8f093'
down_revision = 'cf888d3f2a72'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'loc_zip')
    op.drop_column('shows', 'loc_state')
    op.drop_column('shows', 'song_performance_note')
    op.add_column('songs', sa.Column('written_by', sa.String(length=200), nullable=True))
    op.add_column('venues', sa.Column('phone', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'phone')
    op.drop_column('songs', 'written_by')
    op.add_column('shows', sa.Column('song_performance_note', mysql.TEXT(), nullable=True))
    op.add_column('shows', sa.Column('loc_state', mysql.VARCHAR(length=4), nullable=True))
    op.add_column('shows', sa.Column('loc_zip', mysql.VARCHAR(length=10), nullable=True))
    ### end Alembic commands ###
