"""empty message

Revision ID: de99292ab116
Revises: 6a97fb1ae83d
Create Date: 2016-02-24 19:38:03.567367

"""

# revision identifiers, used by Alembic.
revision = 'de99292ab116'
down_revision = '6a97fb1ae83d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_song_link', sa.Column('segued', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_song_link', 'segued')
    ### end Alembic commands ###
