"""empty message

Revision ID: f3f532a38d0e
Revises: fc26e8c91b89
Create Date: 2016-02-29 23:33:00.034192

"""

# revision identifiers, used by Alembic.
revision = 'f3f532a38d0e'
down_revision = 'fc26e8c91b89'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'times_played')
    op.drop_column('venues', 'show_count')
    op.drop_column('venues', 'date_first_played')
    op.drop_column('venues', 'date_last_played')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('date_last_played', mysql.DATETIME(), nullable=True))
    op.add_column('venues', sa.Column('date_first_played', mysql.DATETIME(), nullable=True))
    op.add_column('venues', sa.Column('show_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('times_played', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
