"""empty message

Revision ID: fc26e8c91b89
Revises: 7af9adda1b64
Create Date: 2016-02-29 22:46:44.201282

"""

# revision identifiers, used by Alembic.
revision = 'fc26e8c91b89'
down_revision = '7af9adda1b64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('times_played', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('date_first_played', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('date_last_played', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('show_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'show_count')
    op.drop_column('venues', 'date_last_played')
    op.drop_column('venues', 'date_first_played')
    op.drop_column('songs', 'times_played')
    ### end Alembic commands ###
