# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_order', models.IntegerField(default=1)),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ('date', 'date_order'),
            },
        ),
        migrations.CreateModel(
            name='ShowSongLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField()),
                ('set', models.IntegerField()),
                ('notes', models.TextField()),
                ('is_segued', models.BooleanField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Show')),
            ],
            options={
                'ordering': ('track_number',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('is_cover', models.BooleanField()),
                ('lyrics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loc_city', models.CharField(max_length=100)),
                ('loc_state', models.CharField(max_length=5)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('is_closed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='showsonglink',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Song'),
        ),
        migrations.AddField(
            model_name='show',
            name='songs',
            field=models.ManyToManyField(through='setlists.ShowSongLink', to='setlists.Song'),
        ),
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setlists.Venue'),
        ),
    ]
