# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200),
            preserve_default=False,
        ),
    ]
