# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 19:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0004_auto_20161208_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
