# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setlists', '0005_auto_20161208_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='showsonglink',
            name='is_segued',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='showsonglink',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='showsonglink',
            name='set',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_cover',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
